main: tr.com.infumia.dantero.fakeplayer.Core
name: FakePlayer
version: ${project.version}
description: ${project.description}
api-version: '1.13'
authors:
  - Dantero
commands:
  fakeplayer:
    description: Main command of the plugin.
    permission: fakeplayer.command.main
    permission-message: You don't have permission!
    usage: /<command> [help|version|reload|menu]
    aliases:
      - fp